[tools]
node = ["24", "22"]
"npm:firebase-tools" = "latest"
"npm:@googleworkspace/cli" = "latest"
terraform = "latest"
rust = "latest"
go = "1.25"
bun = "latest"
"npm:prettier" = "latest"
"npm:@modelcontextprotocol/server-puppeteer" = "latest"
"github:Nimblesite/deslop" = "latest"
cmake = "latest"
