[tools]
node = ["24", "22"]
"npm:firebase-tools" = "latest"
"npm:@googleworkspace/cli" = "latest"
terraform = "latest"
rust = "latest"
go = "1.25"
bun = "latest"
"npm:prettier" = "3.9.6"
"npm:@modelcontextprotocol/server-puppeteer" = "latest"
cmake = "latest"
duckdb = "latest"
ruby = "latest"
pnpm = "latest"
"ubi:bytecodealliance/wasm-tools" = "latest"
